name: movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_screenutil: ^5.9.3
  go_router: ^16.2.0
  easy_localization: ^3.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  internet_connection_checker: ^3.0.1
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.1
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900

